config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'project_report', :to => 'project_report#index'

app/models/project_query.rb
# Redmine - project management software
# Copyright (C) 2006-2017  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class ProjectQuery < Query

  self.queried_class = Project
  self.view_permission = :search_project

  self.available_columns = [
    QueryColumn.new(:name, :sortable => "#{Project.table_name}.name"),
    QueryColumn.new(:status, :sortable => "#{Project.table_name}.status"),
    QueryColumn.new(:short_description, :sortable => "#{Project.table_name}.description", :caption => :field_description),
    QueryColumn.new(:homepage, :sortable => "#{Project.table_name}.homepage"),
    QueryColumn.new(:identifier, :sortable => "#{Project.table_name}.identifier"),
    QueryColumn.new(:parent, :sortable => "#{Project.table_name}.lft ASC", :default_order => 'desc', :caption => :field_parent),
    QueryColumn.new(:is_public, :sortable => "#{Project.table_name}.is_public", :groupable => true),
    QueryColumn.new(:created_on, :sortable => "#{Project.table_name}.created_on", :default_order => 'desc'),
    QueryColumn.new(:spent_budget, :inline => false),
    QueryColumn.new(:estimated_budget, :inline => false),
    QueryColumn.new(:estimated_income, :inline => false),
    QueryColumn.new(:actual_income, :inline => false),
    QueryColumn.new(:time_progress, :inline => false),
    QueryColumn.new(:actual_progress, :inline => false),
    QueryColumn.new(:total_estimated_hours, :inline => false)
  ]

  def initialize(attributes=nil, *args)
    super attributes
    self.filters ||= { 'status' => {:operator => "=", :values => ['1']} }
  end

  def initialize_available_filters
    add_available_filter "status",
      :type => :list, :values => lambda { project_statuses_values }
    add_available_filter("id",
      :type => :list, :values => lambda { project_values }, :label => :field_project
    )
    add_available_filter "name", :type => :text
    add_available_filter "description", :type => :text
    add_available_filter("parent_id",
      :type => :list_subprojects, :values => lambda { project_values }, :label => :field_parent
    )
    add_available_filter "is_public",
      :type => :list,
      :values => [[l(:general_text_yes), "1"], [l(:general_text_no), "0"]]
    add_available_filter "created_on", :type => :date_past
    add_custom_fields_filters(ProjectCustomField.all)
  end

  def available_columns
    return @available_columns if @available_columns
    @available_columns = self.class.available_columns.dup
    @available_columns += ProjectCustomField.visible.
                            map {|cf| QueryAssociationCustomFieldColumn.new(:project, cf) }
    @available_columns
  end

  def available_display_types
    ['board', 'list']
  end

  def default_columns_names
    @default_columns_names = [:name, :identifier, :short_description]
  end

  def default_sort_criteria
    [['lft', 'desc']]
  end

  def base_scope
    Project.visible.where(statement)
  end

  def results_scope(options={})
    order_option = [group_by_sort_order, (options[:order] || sort_clause)].flatten.reject(&:blank?)

    scope = base_scope.
      order(order_option).
      joins(joins_for_order_statement(order_option.join(',')))

    if has_custom_field_column?
      scope = scope.preload(:custom_values)
    end

    if has_column?(:parent_id)
      scope = scope.preload(:parent)
    end

    scope
  end

  # Returns a scope of project statuses that are available as columns or filters
  def project_statuses_values
    [
      [l(:project_status_active), "#{Project::STATUS_ACTIVE}"],
      [l(:project_status_closed), "#{Project::STATUS_CLOSED}"]
    ]
  end
end

app/controllers/project_report_controller.rb
class ProjectReportController < ApplicationController
  menu_item :overview
  menu_item :settings, :only => :settings
  menu_item :projects, :only => [:index, :new, :copy, :create]

  before_action :find_project, :except => [ :index, :autocomplete, :list, :new, :create, :copy ]
  before_action :authorize, :except => [ :index, :autocomplete, :list, :new, :create, :copy, :archive, :unarchive, :destroy]
  before_action :authorize_global, :only => [:new, :create]
  before_action :require_admin, :only => [ :copy, :archive, :unarchive, :destroy ]
  accept_rss_auth :index
  accept_api_auth :index, :show, :create, :update, :destroy
  require_sudo_mode :destroy

  helper :custom_fields
  helper :issues
  helper :queries
  include QueriesHelper
  helper :repositories
  helper :members
  helper :projects

  def index
    # try to redirect to the requested menu item
    if params[:jump] && redirect_to_menu_item(params[:jump])
      return
    end

    retrieve_project_query
    scope = project_scope

    respond_to do |format|
      format.html {
        @entry_count = scope.count
        @entry_pages = Paginator.new @entry_count, per_page_option, params['page']
        @entries = scope.offset(@entry_pages.offset).limit(@entry_pages.per_page).to_a
      }
      format.api  {
        @offset, @limit = api_offset_and_limit
        @project_count = scope.count
        @projects = scope.offset(@offset).limit(@limit).to_a
      }
      format.atom {
        projects = scope.reorder(:created_on => :desc).limit(Setting.feeds_limit.to_i).to_a
        render_feed(projects, :title => "#{Setting.app_title}: #{l(:label_project_latest)}")
      }
      format.csv {
        # Export all entries
        @entries = scope.to_a
        send_data(query_to_csv(@entries, @query, params), :type => 'text/csv; header=present', :filename => 'projects.csv')
      }
    end
  end

  private

  # Returns the ProjectEntry scope for index
  def project_scope(options={})
    @query.results_scope(options)
  end

  def retrieve_project_query
    retrieve_query(ProjectQuery, false)
  end
end

app/helpers/project_report_helper.rb
module ProjectReportHelper
end

app/views/project_query/_board.html.erb
<div id="projects-index">
  <%= render_project_hierarchy(@entries) %>
</div>

app/views/project_query/_list.html.erb
<div class="autoscroll">
<table class="list projects odd-even <%= @query.css_classes %>">
<thead>
  <tr>
    <% @query.inline_columns.each do |column| %>
      <%= column_header(@query, column) %>
    <% end %>
  </tr>
</thead>
<tbody>
<% grouped_project_list(entries, @query) do |entry, level, group_name, group_count, group_totals| -%>
  <% if group_name %>
    <% reset_cycle %>
    <tr class="group open">
      <td colspan="<%= @query.inline_columns.size %>">
        <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
        <span class="name"><%= group_name %></span>
        <% if group_count %>
        <span class="count"><%= group_count %></span>
        <% end %>
        <span class="totals"><%= group_totals %></span>
        <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                             "toggleAllRowGroups(this)", :class => 'toggle-all') %>
      </td>
    </tr>
  <% end %>
  <tr id="project-<%= entry.id %>" class="<%= cycle('odd', 'even') %> <%= entry.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    <% @query.inline_columns.each do |column| %>
    <%= content_tag('td', column_content(column, entry), :class => column.css_classes) %>
    <% end %>
  </tr>

  <% @query.block_columns.each do |column| %>
    <% if (text = column_content(column, entry)) && text.present? -%>
      <tr class="<%= current_cycle %>">
        <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>">
          <% if @query.block_columns.count > 1 %>
            <span><%= column.caption %></span>
          <% end %>
          <%= text %>
        </td>
      </tr>
    <% end -%>
  <% end -%>
<% end -%>
</tbody>
</table>
</div>

app/views/project_query/_query_form.html.erb
<%= hidden_field_tag 'set_filter', '1' %>
<%= hidden_field_tag 'type', @query.type, :disabled => true, :id => 'query_type' %>
<%= query_hidden_sort_tag(@query) %>

<div id="query_form_with_buttons" class="hide-when-print">
  <div id="query_form_content">
    <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
      <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
      <div style="<%= @query.new_record? ? "" : "display: none;" %>">
        <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
      </div>
    </fieldset>

    <% if @query.available_columns.any? %>
      <fieldset id="options" class="collapsible collapsed">
        <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
        <div class="hidden">
          <% if @query.available_display_types.size > 1 %>
            <div>
              <span class="field"><label for='display_type'><%= l(:label_display_type) %></label></span>
              <%= available_display_types_tags(@query) %>
            </div>
          <% end %>
          <table id="list" class="<%= 'hidden' if (@query.display_type == 'board') %>">
            <% if @query.available_columns.any? %>
              <tr>
                <td class="field"><%= l(:field_column_names) %></td>
                <td><%= render_query_columns_selection(@query) %></td>
              </tr>
            <% end %>
            <% if @query.groupable_columns.any? %>
              <tr>
                <td class="field"><label for='group_by'><%= l(:field_group_by) %></label></td>
                <td><%= group_by_column_select_tag(@query) %></td>
              </tr>
            <% end %>
            <% if @query.available_block_columns.any? %>
              <tr>
                <td class="field"><%= l(:button_show) %></td>
                <td><%= available_block_columns_tags(@query) %></td>
              </tr>
            <% end %>
            <% if @query.available_totalable_columns.any? %>
              <tr>
                <td><%= l(:label_total_plural) %></td>
                <td><%= available_totalable_columns_tags(@query) %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </fieldset>
    <% end %>
  </div>

  <p class="buttons">
    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :sort => '', :project_id => @project }, :class => 'icon icon-reload'  %>
    <% if @query.new_record? %>
      <% if User.current.allowed_to?(:save_queries, @project, :global => true) %>
        <%= link_to_function l(:button_save),
                             "$('#query_type').prop('disabled',false);$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit()",
                             :class => 'icon icon-save' %>
      <% end %>
    <% else %>
      <% if @query.editable_by?(User.current) %>
        <%= link_to l(:button_edit), edit_query_path(@query), :class => 'icon icon-edit' %>
        <%= delete_link query_path(@query) %>
      <% end %>
    <% end %>
  </p>
</div>

<%= error_messages_for @query %>

<%= javascript_tag do %>
  $(function ($) {
  $('#display_type').change(function (e) {
  var option = $(e.target).val()
  if (option == 'board') {
  $('table#list').hide();
  } else {
  $('table#list').show();
  }

  })
  });

<% end %>

app/views/project_query/_sidebar.html.erb
<%= render_sidebar_queries(ProjectQuery, @project) %>
<%= call_hook(:view_projects_sidebar_queries_bottom) %>

app/views/project_report/index.html.erb
<div class="contextual">
  <%= form_tag({}, :method => :get) do %>
  <% end %>
  <%= render_project_action_links %>
</div>

<h2><%= @query.new_record? ? l(:label_project_plural) : @query.name %></h2>

<%= form_tag(project_report_path(@project, nil), :method => :get, :id => 'query_form') do %>
  <%= render :partial => 'project_query/query_form' %>
<% end %>

<% if @query.valid? %>
  <% if @entries.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render :partial => 'project_query/'+@query.display_type, :locals => { :entries => @entries }%>
    <span class="pagination"><%= pagination_links_full @entry_pages, @entry_count %></span>
  <% end %>
<% end %>

<% if User.current.logged? %>
  <p style="text-align:right;">
    <span class="icon icon-fav my-project"><%= l(:label_my_projects) %></span>
  </p>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'project_query/sidebar' %>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => {:key => User.current.rss_key} %>
<% end %>

<% html_title(l(:label_project_plural)) -%>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'style.css', plugin: :sarmad_project_report %>
<% end %>